package models

import (
	"time"

	"github.com/google/uuid"
)

type Parcel struct {
	ID             uuid.UUID  `gorm:"type:uuid;primary_key;default:gen_random_uuid()"`
	Name           string     `gorm:"not null"`
	Description    string
	Geometry       string     `gorm:"type:geometry(Polygon,4326);not null"`
	AreaHa         float64    `gorm:"->"` // Generated by DB
	CountryCode    string     `gorm:"type:char(2)"`
	SourceURL      string
	GeometryLocked bool       `gorm:"default:false"`
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Snapshots      []Snapshot `gorm:"foreignKey:ParcelID"`
}
